### ISSUE TITLE
Formatting questions and suggestions

### ISSUE THREAD

**Issue by vasilygrz** [edzer/sdsr#108]
Hi @edzer,

I'm learning spatial statistics and I'd like to, first of all, thank you and @rsbivand for publishing this open access book. Currently, I've read more than half of it and I'd to ask the following questions:

1. What style guide are you following?
2. Why function arguments within the text end in `=`? For example, '`Durbin=` argument' from [Ch. 17](https://github.com/edzer/sdsr/blob/4774a69e474c29379708e3d6b8f385ab5530bac0/17-Econometrics.qmd#L79C36-L79C36).
Would removing them create unnecessary confusion?

Regarding the style guide, I've noticed that dashes aren't used in the text. Following the _New Hart's Rules: The Oxford Style Guide_ (2014), which I use as a reference, we can choose between en (`&ndash;`) or em (`&mdash;`) dashes.

> 4.11.1 En rule (p. 86)
The en rule (US en dash) (–) is longer than a hyphen and half the length of an em rule (—). Many British publishers use an en rule with space either side as a parenthetical dash, but Oxford and most US publishers use an em rule.

If we chose the en rule, this is how it would look like (Examples from Ch. 1):

- 'Figure 1.1: A first map: birth counts 1974–78, North Carolina counties' [[1](https://github.com/edzer/sdsr/blob/4774a69e474c29379708e3d6b8f385ab5530bac0/01-hello.qmd#L16)]
- 'When we have longer time series associated with geometries, neither option – distributing time over multiple columns, or stacking columns while repeating geometries – works well, and a more effective way of storing such data would be a matrix or array, where one dimension refers to time, and the other(s) to space.' [[2](https://github.com/edzer/sdsr/blob/4774a69e474c29379708e3d6b8f385ab5530bac0/01-hello.qmd#L354C474-L354C474)]

Similarly, there are a few typos regarding linking chapters. Instead of [[3](https://github.com/edzer/sdsr/blob/4774a69e474c29379708e3d6b8f385ab5530bac0/08-Plotting.qmd#L472)]
> is shown in @fig-tmapstars. More examples of the use of **tmap** are given in Chapters -@sec-area - -@sec-spatglmm.

it should be
> is shown in @fig-tmapstars. More examples of the use of **tmap** are given in @sec-area&ndash;@sec-spatglmm.

It also happens in [10.2 Support and statistical modelling](https://github.com/edzer/sdsr/blob/4774a69e474c29379708e3d6b8f385ab5530bac0/10-Models.qmd#L123).

I can correct this punctuation issue if you want me to.

**Comment by edzer** [comment]
Thanks. We didn't follow an external style guide. I think in text, `Durbin=` should be `Durbin`, but I'm hesitant to introduce dashes where there currently aren't. The chapter linking typos can be a result of fixes/changes in `quarto`, corrections are very welcome!

**Comment by vasilygrz** [comment]
Thank you for response, @edzer.

1. The `=` sign after the argument can be found in Ch. 14-17. Can I remove them?
2. Adding dashes would be the proper thing to do from a grammatical point of view. I'd also have to add them to correct the chapter linking typos. Can I do it?

**Comment by edzer** [comment]
1. Yes; 2: only to correct chapter linking typos.
