### ISSUE TITLE
spdep issue Ch 17

### ISSUE THREAD

**Issue by edzer** [edzer/sdsr#121]
See https://github.com/edzer/sdsr_exercises/actions/runs/7824811792/job/21347983478#step:8:506

Is this caused by the new spdep on CRAN? @rsbivand

**Comment by rsbivand** [comment]
PR https://github.com/edzer/sdsr_exercises/pull/3 should fix this - added conditioning on spdep version and edited function call and test names. See also https://github.com/r-spatial/spdep/commit/208f1b3bb27f52865afd0d11497dd179509b728f which is a permanent fix from next spdep release.
