### ISSUE TITLE
Can't rebuild book, no aq files on repo

### ISSUE THREAD

**Issue by rsbivand** [edzer/sdsr#27]
Should I download my own aq files to be able to rebuild the whole book to check the formatting in ch 17-18?

**Comment by edzer** [comment]
Good question: 2.5 Gb, with the population density grid 1.3 Gb: I don't think Github allows to add files this size. I've put them here, for the moment: http://gis-bigdata.uni-muenster.de/aq.tar.gz

**Comment by edzer** [comment]
... but you'll need [this](https://github.com/edzer/spacetime/commit/c68abad73f64320249e73f68b01ac6fe1f3b0f50), i.e. `spacetime` from github, otherwise it'll break.
