### ISSUE TITLE
Add content about containers

### ISSUE THREAD

**Issue by nuest** [edzer/sdsr#28]
Have you considered adding a short chapter, on the same level as "R data structures" chapter?

I think the installation of geospatial packages has made a huge leap forward, but there still might be times or reasons where readers of the book would profit from a quick introduction in the the [`rocker/geospatial´](https://github.com/rocker-org/geospatial/) images.

This section could also extend a bit on the idea of reproducibility, which so far is only mentioned in the preface.

**Comment by edzer** [comment]
In https://github.com/edzer/sdsr/tree/main/docker
