### ISSUE TITLE
Do you have a plan to publish?

### ISSUE THREAD

**Issue by su-park** [edzer/sdsr#41]
I studied a few pieces of puzzle of 'Spatial data science' from here and there

( It's always not enough for me. )

and found your draft by accident.

It is to me something like '101 stuff for practical spatial data science'

I really enjoyed reading your draft.

Thank you for sharing such a great work!

Do you have any plan to publish the book? (when?)

I am eager to know it and buy one.

**Comment by edzer** [comment]
Thanks! Yes, the plan is to publish it as a book, hopefully soon. If you have any recommendations, like things you were missing when reading it or things that were too complex or over-elaborate, please let us know!
