### ISSUE TITLE
stuck at 5090-5092 (sds.Rmd)

### ISSUE THREAD

**Issue by rsbivand** [edzer/sdsr#61]
I have the vector PostgreSQL driver but not PostGIS. I do not  want to install PostGIS (because it depends on GDAL/GEOS/PROJ which I install from source and change frequently). The `has_PG` test doesn't check that the driver works. How to skip these sections?

**Comment by edzer** [comment]
I extended the test now to checking that the database is present, so should work more portably.

**Comment by rsbivand** [comment]
Thanks. Next blockages were development version of **gstat** (OK), then I tried to use the development version of **stars** to tackle:

```
label: unnamed-chunk-136
Quitting from lines 6475-6484 (sds.Rmd) 
Error: Scale limits cannot be mapped onto spatial coordinates in `coord_sf()`.
Consider setting `lims_method = "geometry_bbox"` or `default_crs = NULL`.
```
about which I have no idea as tidyverse and ggplot are not my friends. I'm running **sf** development version.

**Comment by edzer** [comment]
Ah, is this ggplot2 version 3.3.4?

**Comment by rsbivand** [comment]
```
> packageVersion("ggplot2")
[1] '3.3.4'
```

**Comment by edzer** [comment]
Thanks, that should work now.
