### ISSUE TITLE
Some additional comments to chapters 8 and 9

### ISSUE THREAD

**Issue by Nowosad** [edzer/sdsr#69]
Chapter 8:

- Gb or GB? Tb or TB? You use Gb and Tb, but (correct me if I am wrong) I think it should be GB and TB
- `" In such cases it may be most helpful to either gain access to (typically: rent) virtual machines in a cloud
where these data are available and nearby"` - there is something wrong with this sentence...

Chapter 9:

- You use "color" in some sentences and "colour" in others...
- `"Good colors scales are e.g. found in packages `RColorBrewer` [@R-RColorBrewer], viridis [@R-viridis] or colorspace [@R-colorspace; @colorspace]."` - maybe it is worth to mention the `hcl.colors` and `palette.colors` functions as they have all of the palettes methioned before...
- A few figure captions are not completed, for example `"fig captions tmap: using ..."`
- \@ref(fig:mapviewfigure) is broken

**Comment by edzer** [comment]
Thanks!

> @ref(fig:mapviewfigure) is broken

I've seen in Figure 8.18 of geocomp how complicated this is!
