### ISSUE TITLE
Missing data in aq folder for 12.7.1 A population grid

### ISSUE THREAD

**Issue by williamlai2** [edzer/sdsr#82]
[12.7.1 A population grid](https://keen-swartz-3146c4.netlify.app/interpolation.html#a-population-grid) refers to:

```
v = vroom::vroom("aq/pop/Zensus_Bevoelkerung_100m-Gitter.csv")
```

And [13.1 Preparing the air quality dataset](https://keen-swartz-3146c4.netlify.app/stgeostatistics.html#preparing) refers to:
```
library(tidyverse)
read.csv("aq/AirBase_v8_stations.csv", sep = "\t") %>% 
    as_tibble()  %>% 
    filter(country_iso_code == "DE", station_type_of_area == "rural", 
                 type_of_station == "Background") -> a2
```
But they are not in here: https://github.com/edzer/sdsr/tree/main/aq

**Comment by edzer** [comment]
Yes, this is a bit too large for GitHub I believe; for now available from https://uni-muenster.sciebo.de/s/8mEbeHPOX9GdAYn

**Comment by williamlai2** [comment]
Thanks
