### ISSUE TITLE
Tiny typo in Point Pattern Analysis

### ISSUE THREAD

**Issue by Lvulis** [edzer/sdsr#83]
In the following bullet point in the first section of Ch 11 there's a small typo, I guess it should be "they".

> second order properties, e.g. pairwise interactions: given a constant or varying intensity function, are points distributed independently from one another, or do **the** tend to attract each other (clustering) or repulse each other (appear regularly distributed, compared to independence)

**Comment by edzer** [comment]
Thanks!
